# Generated by Django 2.0.1 on 2018-04-27 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_server', '0002_auto_20180419_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
