# Generated by Django 2.0.5 on 2018-05-17 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_server', '0004_auto_20180507_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question_server.Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='mark',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='some_name', max_length=200),
            preserve_default=False,
        ),
    ]
